#DEFLITERAL 'EL valor de exito: '
#DEFLITERAL 'EL valor de x: '
#DEFLITERAL 'EL valor de y: '
#DEFLITERAL 'EL valor de j: '
#DEFLITERAL '
'
*1
RESERVAESP 0
CLITERAL 19 0
GRABACIONLITERAL
CDIRLOCAL 2
CINDVALOR 1
CINDVALOR 1
GRABACION
CLITERAL 2 4
GRABACIONLITERAL
CDIRLOCAL 2
CINDVALOR 1
CINDVALOR 1
NEGACION
CDIRLOCAL 2
CINDVALOR 1
AINDVALOR 1
CLITERAL 19 0
GRABACIONLITERAL
CDIRLOCAL 2
CINDVALOR 1
CINDVALOR 1
GRABACION
CLITERAL 2 4
GRABACIONLITERAL
DEVOLUCION 2
*2
RESERVAESP 0
CLITERAL 19 0
GRABACIONLITERAL
CDIRLOCAL 4
CINDVALOR 1
CINDVALOR 1
GRABACION
CLITERAL 2 4
GRABACIONLITERAL
CDIRLOCAL 3
CDIRLOCAL 4
CINDVALOR 1
LLAMADA 1
CLITERAL 19 0
GRABACIONLITERAL
CDIRLOCAL 4
CINDVALOR 1
CINDVALOR 1
GRABACION
CLITERAL 2 4
GRABACIONLITERAL
DEVOLUCION 3
*0
#TAMGLOBAL 5
#TAMFUNCION 0
CCONSTANTE 7
CCONSTANTE 3
MAYOR
CCONSTANTE 3
CCONSTANTE 7
MAYOR
CONJUNCION
CDIRGLOBAL 4
AINDVALOR 1
CCONSTANTE 3
CDIRGLOBAL 0
AINDVALOR 1
CLITERAL 19 0
GRABACIONLITERAL
CDIRGLOBAL 4
CINDVALOR 1
GRABACION
CLITERAL 2 4
GRABACIONLITERAL
CDIRGLOBAL 4
CDIRGLOBAL 0
CINDVALOR 1
CDIRGLOBAL 2
LLAMADA 2
CLITERAL 19 0
GRABACIONLITERAL
CDIRGLOBAL 4
CINDVALOR 1
GRABACION
CLITERAL 2 4
GRABACIONLITERAL
CDIRGLOBAL 1
CDIRGLOBAL 4
LLAMADA 1
CLITERAL 19 0
GRABACIONLITERAL
CDIRGLOBAL 4
CINDVALOR 1
GRABACION
CLITERAL 2 4
GRABACIONLITERAL
TERMINACION