#DEFLITERAL '
'
*1
RESERVAESP 0
CCONSTANTE 2
LIMITACION  5 0
CDIRLOCAL 2
CINDVALOR 1
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CCONSTANTE 2
CCONSTANTE 4
LIMITACION 1 5 1
CDIRLOCAL 2
CINDVALOR 1
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 2
LIMITACION 1 5 0
CDIRLOCAL 2
CINDVALOR 1
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
DEVOLUCION 1
*0
#TAMGLOBAL 10
#TAMFUNCION 0
CCONSTANTE 1
CCONSTANTE 1
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 2
CCONSTANTE 2
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 3
CCONSTANTE 3
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 4
CCONSTANTE 4
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 5
CCONSTANTE 5
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 2
LIMITACION 1 5 0
CDIRGLOBAL 0
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CDIRGLOBAL 0
LLAMADA 1
CCONSTANTE 2
LIMITACION 1 5 0
CDIRGLOBAL 0
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
TERMINACION