#DEFLITERAL 'X vale: '
#DEFLITERAL 'Y vale: '
#DEFLITERAL 'Z vale: '
#DEFLITERAL 'M vale: '
#DEFLITERAL '
'
*1
RESERVAESP 2
CDIRLOCAL 3
CINDVALOR 1
CINDVALOR 2
CDIRLOCAL 2
CINDVALOR 1
CINDVALOR 2
SUMAREAL
CDIRLOCAL -2
AINDVALOR 2
CLITERAL 8 2
GRABACIONLITERAL
CDIRLOCAL -2
CINDVALOR 2
GRABACIONREAL
CLITERAL 2 4
GRABACIONLITERAL
CDIRLOCAL -2
CINDVALOR 2
CCONSTANTE 2
AREAL 0
PRODUCTOREAL
CDIRLOCAL 3
CINDVALOR 1
AINDVALOR 2
CLITERAL 8 2
GRABACIONLITERAL
CDIRLOCAL -2
CINDVALOR 2
GRABACIONREAL
CLITERAL 2 4
GRABACIONLITERAL
CDIRLOCAL -2
CINDVALOR 2
CCONSTANTE 4
AREAL 0
SUMAREAL
CCONSTANTE 5
AREAL 0
MODULOREAL
CDIRLOCAL -2
AINDVALOR 2
CLITERAL 8 2
GRABACIONLITERAL
CDIRLOCAL -2
CINDVALOR 2
GRABACIONREAL
CLITERAL 2 4
GRABACIONLITERAL
DEVOLUCION 2
*0
#TAMGLOBAL 8
#TAMFUNCION 0
CCONSTANTEREAL 2.7
CDIRGLOBAL 0
AINDVALOR 2
CCONSTANTEREAL 3.2
CDIRGLOBAL 2
AINDVALOR 2
CDIRGLOBAL 0
CDIRGLOBAL 2
LLAMADA 1
CLITERAL 8 0
GRABACIONLITERAL
CDIRGLOBAL 0
CINDVALOR 2
GRABACIONREAL
CLITERAL 2 4
GRABACIONLITERAL
CDIRGLOBAL 0
CINDVALOR 2
CDIRGLOBAL 2
CINDVALOR 2
PRODUCTOREAL
CCONSTANTE 2
AREAL 0
DIVISIONREAL
CDIRGLOBAL 2
AINDVALOR 2
CLITERAL 8 1
GRABACIONLITERAL
CDIRGLOBAL 2
CINDVALOR 2
GRABACIONREAL
CLITERAL 2 4
GRABACIONLITERAL
TERMINACION