*0
#TAMGLOBAL 4
#TAMFUNCION 0
CCONSTANTE 1
CCONSTANTE 5
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 2
CCONSTANTE 4
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 3
CCONSTANTE 3
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 4
CCONSTANTE 2
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 5
CCONSTANTE 1
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 1
LIMITACION 1 5 0
CDIRGLOBAL 0
DELEMENTO 1 1
CINDVALOR 4
GRABACION
CCONSTANTE 4
LIMITACION 1 5 0
CDIRGLOBAL 0
DELEMENTO 1 1
CINDVALOR 4
GRABACION
CCONSTANTE 5
LIMITACION 1 5 0
CDIRGLOBAL 0
DELEMENTO 1 1
CINDVALOR 4
GRABACION
TERMINACION