#DEFLITERAL '
'
*0
#TAMGLOBAL 16
#TAMFUNCION 0
CCONSTANTE 1
CCONSTANTE 5
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 2
CCONSTANTE 4
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 3
CCONSTANTE 3
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 4
CCONSTANTE 2
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 5
CCONSTANTE 1
LIMITACION 1 5 1
CDIRGLOBAL 0
DELEMENTO 1 1
AINDVALOR 1
CCONSTANTE 1
LIMITACION 1 5 0
CDIRGLOBAL 0
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CCONSTANTE 2
LIMITACION 1 5 0
CDIRGLOBAL 0
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CCONSTANTE 3
LIMITACION 1 5 0
CDIRGLOBAL 0
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CCONSTANTE 4
LIMITACION 1 5 0
CDIRGLOBAL 0
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CCONSTANTE 5
LIMITACION 1 5 0
CDIRGLOBAL 0
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CDIRGLOBAL 0
CINDVALOR 5
CDIRGLOBAL 5
AINDVALOR 5
CCONSTANTE 1
LIMITACION 1 5 0
CDIRGLOBAL 5
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CCONSTANTE 2
LIMITACION 1 5 0
CDIRGLOBAL 5
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CCONSTANTE 3
LIMITACION 1 5 0
CDIRGLOBAL 5
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CCONSTANTE 4
LIMITACION 1 5 0
CDIRGLOBAL 5
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CCONSTANTE 5
LIMITACION 1 5 0
CDIRGLOBAL 5
DELEMENTO 1 1
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CCONSTANTE 3
CDIRGLOBAL 10
DCAMPO 0
AINDVALOR 1
CCONSTANTEREAL 4.76754
CDIRGLOBAL 10
DCAMPO 1
AINDVALOR 2
CDIRGLOBAL 10
DCAMPO 0
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CDIRGLOBAL 10
DCAMPO 1
CINDVALOR 2
GRABACIONREAL
CLITERAL 2 0
GRABACIONLITERAL
CDIRGLOBAL 10
CINDVALOR 3
CDIRGLOBAL 13
AINDVALOR 3
CDIRGLOBAL 13
DCAMPO 0
CINDVALOR 1
GRABACION
CLITERAL 2 0
GRABACIONLITERAL
CDIRGLOBAL 13
DCAMPO 1
CINDVALOR 2
GRABACIONREAL
CLITERAL 2 0
GRABACIONLITERAL
TERMINACION