#DEFLITERAL 'Introduzca el valor para x: '
#DEFLITERAL 'x vale: '
#DEFLITERAL '
'
*0
#TAMGLOBAL 1
#TAMFUNCION 0
CLITERAL 28 0
GRABACIONLITERAL
CDIRGLOBAL 0
LECTURA
CLITERAL 8 1
GRABACIONLITERAL
CDIRGLOBAL 0
CINDVALOR 1
GRABACION
CLITERAL 2 2
GRABACIONLITERAL
TERMINACION